site_name: Diagho Documentation
site_author: DiaghoProject
copyright: 2020 - 2021 © DiaghoProject
site_url: https://docs.diagho.com/
repo_name: DiaghoProject/docs
repo_url: https://github.com/DiaghoProject/docs
edit_uri: 'edit/main/src/'
docs_dir: 'src'
site_dir: 'docs'
theme:
  language: en
  name: material
  custom_dir: overrides/material
  palette:
    primary: deep purple
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  logo: images/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.indexes
plugins:
  - search:
      lang:
        - fr
        - en
  - awesome-pages
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - attr_list
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DiaghoProject
      name: DiaghoProject on GitHub
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
